name: deploy demo app

on:
  push:
    branches:
      - master

env:
  OCI_CLI_USER: 'ocid1.user.oc1..aaaaaaaaclga66dcd36wd4lhv35rd4zljvhyvpnxiwysgpn43ehe6ehkukcq'
  OCI_CLI_TENANCY: 'ocid1.tenancy.oc1..aaaaaaaapjiukwuohcn2ksmdfgcnlcbwennalukq5tgdx5375exrpoydxrda'
  OCI_CLI_FINGERPRINT: '3b:1e:ab:e2:e9:80:99:94:68:8d:66:3d:49:a6:98:fd'
  OCI_CLI_KEY_CONTENT: | '-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDK7kJKUHltuLX0
JX5F8stdCKoZzwpGB8Ea/4ybAdwYEXtgl3oMjyvbr3+V7gnrTQF4T2F8uZLlSqhV
a8IuUMD9SZFRIrKzXnvd88QD9qa0x/BIauS8cEqJjUCR0Y+0UpaA6Z5FETyHOMfo
ILtlMHRElAehyXoLu/oKcXY5ZZiMN/3GGcig0LCR0UYTmJc/+sMcx5ghF7qyucTg
n4L9FffjVCiG8xgTxXi/6iW8vn9XIi9PSo1wYoY5djQmzPU9ZVkjho2mhMWYFh/C
QvaPymPvcdEN4S6+6Fu5h433jFVLWm85t5bjYEXsxHRYMtvUk+ruDMeQT+fIFLv6
00SOcQDvAgMBAAECggEAEzCr0SZCDWexwThIdCntJEuc9lrXYF78Wma/L6th2l7Q
2YYJkyV44sn6WT3M71T1ZiCvmeFcrFU+jPFnSAT38xvhY5hR6NdvBEK4jx1kj2T2
6oo9PjqqOc7DQ+ba3ZUPyXoOLv7dx/XNJbzuq7eEzzVmcVzBr1lj4Ffxc6URY3T+
vrsb0+CCVSY9B9BJqwY1hRJigvmOMs1xCfbmIzl0ZMurNE52RTHwYbgxyvhY2FGh
q3mLOLall33JE42y0BPWnq46m8h0y3q8HQW/ZtqpBe5l82uSQSIE+0n5EkR2L5LN
OPm4ZRIzaVFwqLmQvzM41LX+WQ8CGOQbgDG1V6EfzQKBgQD534Ez/oWmjl6WpKk8
SbQqLvlzs0Z0nqv6ym35IqOBjN+DRdeDykkyF4VjxrGhkLfAUIvSE9fimVZ5XC1y
LTCRX1imIghdx3Sgp3zzOLq5GFxZ5ZUbM4EeDWkpuCtgs7wPXnQ4a7ZfwFzPE7QL
pdJ7LRbIBv3sB/Zw6Kg8tXjKQwKBgQDP6BbP84z6H9f2as/RdXcMc/Qe4QUWEJlU
t3/0oHLEZccn/e+K90FZMrT0Y+E2ZG/DPH16ueFPKuujhYvljGOtH17nNQzKdWx+
7cEu6ixmwzKiD+zV/RwucB9JFAvdcDEQXtQICoweFOhGxWJvvZNmDKR/QWPc5fe8
1q1qJOnx5QKBgEs+YbLdhzOTlao5ZXjxHN7DDH0p1CKUEWfRA3LNWn1NhZULOA3I
oWgDKzjTgXQMlzjDSId3UEA9OowLFOhX8VMlahWFFA3hXR5vsTGwuJG6Yzzy5Iav
aMc69JsKiY1yMkRShh7jWKTW0VvOLB6BzbMn7b9IU7h64Vw4w0icwQXvAoGBAKYA
wnY4GRB97IosrtKn3+5phzpAoTcE+ejSu7AvjHOUcHhWIbXrxpnaCvI37dLoTvSs
j+Q2FtiHhK6EKzeV6OCKc9RYX2YobADNBbrX76v9n6gW3xvdhWruy4wmHXMp6YMQ
tGvXQBmkx/H6GKbvz4lj/tQ8+eefFzgIkV53KvShAoGBANETzOZh1hnkWmWo0IxG
O7Kjbtgwy8fsuhCccfVEjvY/ThNyYtYvH64Gzz70yGCJdxxK0N3cU2rOKMSJyV1J
vEST0eJg2vZ/otiDfqZNYLHPeEHBDJp4xkF/wH3jIyMRcHZ8hVciCyTtdV6IK84F
fR7YbIcujEKD2zleT+fNIh+T
-----END PRIVATE KEY-----'
  OCI_CLI_REGION: 'us-ashburn-1'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Get Access to OCIR
        id: get-ocir
        uses: oracle-actions/get-ocir-repository@v1.0
        with:
          name: ${{ secrets.test.OCI_DOCKER_REPO }}
          compartment: ${{ secrets.test.OCI_COMPARTMENT_OCID }}
      
      - name: Log Into OCIR
        uses: oracle-actions/login-ocir@v1.0
        id: login-ocir
        with:
          auth_token: 'zds]7X6v8(sY<j7).DqK'
      
      - name: Docker Build
        id: docker-build
        run: |
          docker build -t ${{ secrets.test.OCI_DOCKER_REPO }}:${{ github.sha }} .
      
      - name: Docker Push
        id: docker-push
        run: |
          docker push ${{ secrets.test.OCI_DOCKER_REPO }}:${{ github.sha }}
      
      - name: Upload Chart 
        uses: actions/upload-artifact@master
        with:
          name: app-chart-${{ github.sha }}
          path: chart/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download Chart
        uses: actions/download-artifact@master
        with:
          name: app-chart-${{ github.sha }}
          path: chart/

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.0
        id: kubectl-oke-action
        with:
          cluster: ${{ secrets.test.OKE_CLUSTER_OCID }}
      
      - name: Helm Deploy
        id: helm-deploy
        run: |
          helm upgrade \
            demo chart/ \
            --install --wait \
            --values chart/demo.yaml \
            --set image.tag=${{ github.sha }} \
            --namespace demo
