name: deploy demo app

on:
  push:
    branches:
      - master

env:
  OCI_CLI_USER: ocid1.user.oc1..aaaaaaaaclga66dcd36wd4lhv35rd4zljvhyvpnxiwysgpn43ehe6ehkukcq
  OCI_CLI_TENANCY: ocid1.tenancy.oc1..aaaaaaaapjiukwuohcn2ksmdfgcnlcbwennalukq5tgdx5375exrpoydxrda
  OCI_CLI_FINGERPRINT: 3b:1e:ab:e2:e9:80:99:94:68:8d:66:3d:49:a6:98:fd
  OCI_CLI_KEY_CONTENT: ${{ secrets.test.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: us-ashburn-1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Get Access to OCIR
        id: get-ocir
        uses: oracle-actions/get-ocir-repository@v1.0
        with:
          name: ${{ secrets.test.OCI_DOCKER_REPO }}
          compartment: ${{ secrets.test.OCI_COMPARTMENT_OCID }}
      
      - name: Log Into OCIR
        uses: oracle-actions/login-ocir@v1.0
        id: login-ocir
        with:
          auth_token: ${{ secrets.test.OCI_AUTH_TOKEN }}
      
      - name: Docker Build
        id: docker-build
        run: |
          docker build -t ${{ secrets.test.OCI_DOCKER_REPO }}:${{ github.sha }} .
      
      - name: Docker Push
        id: docker-push
        run: |
          docker push ${{ secrets.test.OCI_DOCKER_REPO }}:${{ github.sha }}
      
      - name: Upload Chart 
        uses: actions/upload-artifact@master
        with:
          name: app-chart-${{ github.sha }}
          path: chart/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download Chart
        uses: actions/download-artifact@master
        with:
          name: app-chart-${{ github.sha }}
          path: chart/

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.0
        id: kubectl-oke-action
        with:
          cluster: ${{ secrets.test.OKE_CLUSTER_OCID }}
      
      - name: Helm Deploy
        id: helm-deploy
        run: |
          helm upgrade \
            demo chart/ \
            --install --wait \
            --values chart/demo.yaml \
            --set image.tag=${{ github.sha }} \
            --namespace demo
